package com.cadrie.hibernate.spatial.test.model;

// Generated Aug 9, 2006 9:35:48 PM by Hibernate Tools 3.2.0.beta6a

import com.vividsolutions.jts.geom.Geometry;
import com.vividsolutions.jts.geom.Polygon;

/**
 * Spatialtest generated by hbm2java
 */
public class PolygonEntity implements java.io.Serializable {

    // Fields

    private static final long serialVersionUID = 1L;

    private long id;

    private String name;

    private Polygon geometry;

    // Constructors

    /** default constructor */
    public PolygonEntity() {
    }

    /** minimal constructor */
    public PolygonEntity(long id) {
	this.id = id;
    }

    /** full constructor */
    public PolygonEntity(long id, String name, Geometry geom) {
	this.id = id;
	this.name = name;
	this.geometry = (Polygon)geom;
    }

    // Property accessors
    public long getId() {
	return this.id;
    }

    public void setId(long id) {
	this.id = id;
    }

    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    public Geometry getGeometry() {
	return this.geometry;
    }

    public void setGeometry(Geometry geom) {
	this.geometry = (Polygon)geom;
    }

}
