package org.hibernatespatial.test.model;

// Generated Aug 9, 2006 9:35:48 PM by Hibernate Tools 3.2.0.beta6a

import org.hibernatespatial.mgeom.MultiMLineString;

import com.vividsolutions.jts.geom.Geometry;
import com.vividsolutions.jts.geom.MultiLineString;


/**
 * Spatialtest generated by hbm2java
 */
public class MultiMLineStringEntity implements java.io.Serializable {

	// Fields

	private static final long serialVersionUID = 1L;

	private long id;

	private String name;

	private MultiMLineString geometry;

	// Constructors

	/** default constructor */
	public MultiMLineStringEntity() {
	}

	/** minimal constructor */
	public MultiMLineStringEntity(long id) {
		this.id = id;
	}

	/** full constructor */
	public MultiMLineStringEntity(long id, String name, Geometry geom) {
		this.id = id;
		this.name = name;
		this.geometry = (MultiMLineString) geom;
	}

	// Property accessors
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Geometry getGeometry() {
		return this.geometry;
	}

	public void setGeometry(MultiMLineString geom) {
		this.geometry = geom;
	}

}
